---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato
spec:
  replicas: 2
  selector:
    matchLabels:
      name: deployment
  template:
    metadata:
      name: dev
      labels:
        name: deployment
    spec:
      containers:
        - name: signup
          image: venugopaldr/zomato
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: zomato-svc
spec:
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30070
  selector:
    name: deployment
  type: NodePort
